### ISSUE TITLE
Would it be possible to create a version compatible with MonoDevelop / Unity3d?

### ISSUE THREAD

**Issue by shongololo** [MiloszKrajewski/lz4net#1]
I am quite interested to give this a go in Unity, however, Unity3d uses an older version of mono which is generally only compatible with .NET up to version ~3.0.

Do you possibly have older versions available, or would it be possible to adapt for use with .NET 2 or 3.0?

Thanks.

**Comment by MiloszKrajewski** [comment]
I don't know, I didn't try. As I was aiming for .NET 4 compatibility (meaning XP compatibility) I was never concerned about .NET 3.5 compatibility. Did you try to compile sources for .NET 3.5?

**Comment by shongololo** [comment]
Yes, I tried compiling the LZ4s safe version for .NET 3.5 and it appears to work for my purposes. However, compiling LZ4 does not work because it requires access to the c++ code which Mono doesn't seem able to process.

**Comment by MiloszKrajewski** [comment]
.NET 2 (and 3.5) compatibility added in 1.0.9.93
