### ISSUE TITLE
LZ4.NET Portable on Xamarin Android

### ISSUE THREAD

**Issue by callanh** [MiloszKrajewski/lz4net#10]
First of all, hello and thank you for a portable version of LZ4, in particular for Xamarin Android/iOS.  I am having a problem running on Android (I haven't tested iOS yet).

I am using version:

```
lz4net.1.0.9.93
```

with assemblies:

```
portable-net4+win8+wpa81+MonoAndroid+MonoTouch+Xamarin.iOS
```

and getting this error:

```
System.InvalidProgramException: Invalid IL code in LZ4pn.LZ4Codec:Encode32 (byte*,byte*,int,int): IL_003c: stloc.3   
```

can be reproduced using this code:

``` C#
var MemoryStream = new MemoryStream();

var CompressStream = new LZ4.LZ4Stream(MemoryStream, LZ4.LZ4StreamMode.Compress);
CompressStream.Write(new byte[1] { 0xFF }, 0, 1);

CompressStream.Flush();
```

The exception occurs on the call to Flush. Any advice or suggestions would be appreciated!

**Comment by MiloszKrajewski** [comment]
The only "special" thing about this method is that it uses unsafe (fixed) pointers. I guess it would be more a case for Xamarin (oops... Microsoft) team.

**Comment by callanh** [comment]
Happy to follow it up with Xamarin.  I just wanted to confirm that it wasn't me doing something obviously wrong. Is Xamarin Android something you have tested?  I noticed that you say 'MonoAndroid' and 'Xamarin.iOS' in the assembly folder.  Or is MonoAndroid the same as Xamarin Android?

**Comment by MiloszKrajewski** [comment]
Unfortunatelly, me saying "it works with Xamarin.Android" is a bold statement. I just made sure it compiles with Xamarin.Android portable profile. Although, I often use with Mono on Ubuntu and I had no problems. Never run it Android though. Sorry.

**Comment by callanh** [comment]
Ouch.  Well, I can confirm that it doesn't work on Xamarin Android!  But I am quite interested in helping you to resolve this issue and make your 'bold' statement become true.  Do you have any barriers to getting Xamarin?  If that is inconvenient for you I am willing to test any of your proposed fixes.

**Comment by MiloszKrajewski** [comment]
Thanks for the hint. I'll take a look.

**Comment by MiloszKrajewski** [comment]
It work now (>= 1.0.14.93) on my Nexus 7. If you think it still needs some changes let me know.
