### ISSUE TITLE
Not compatible with .NETStandard,Version=v1.3.

### ISSUE THREAD

**Issue by naster01** [MiloszKrajewski/lz4net#11]
Hi, I updated my standard library to a PCL (Portable class library) to support Framework 4.6 and Universal Windows App but lz4net is not compatible. 

It would be great to use it in a Windows 10 app!

.NETStandard
https://docs.microsoft.com/en-us/dotnet/articles/standard/library

Thx

**Comment by MiloszKrajewski** [comment]
I am still very confused by the whole .NET Core / .NET Standard thing, but I guess it now supports .NET Standard 1.6. Be first to try it and provide some feedback. Cheers.

**Comment by MiloszKrajewski** [comment]
In my opinion version 1.0.14.93 works fine. Let me know if it isn't.
