### ISSUE TITLE
What is the difference between different compression methods?

### ISSUE THREAD

**Issue by NimaAra** [MiloszKrajewski/lz4net#12]
Hi, firstly thanks for this awesome implementation.

I could not find any documentation about the various methods and it would be very useful if public methods and constructors included _XML_ documentation tags with brief summary of what they do.

Can you kindly mention some of the differences between the following compression/de-compression methods (apart from their signature)?

- Using the `LZ4Stream`;
- Using `LZ4Code.Wrap/Unwrap`;
- Using `LZ4Code.Encode/Decode`.

Thank you,
Nima

**Comment by MiloszKrajewski** [comment]
* Encode/Decode: quite low level. You need to provide output buffer and control how many bytes has been actually encoded/decoded. You this only whan you know what you really want to do.

* Wrap/Unwrap: not the best names. Use Encode/Decode but takes byte[] and returns byte[] of adequate size. Use this when you just need to compress small chunks of data, like `Wrap(text.ToUTF8()).ToBase64()`

* Stream: Potentially unlimited size. Has all advantages and disadvantages of Stream.
