### ISSUE TITLE
Compression in Server side (c#) and decompression in Client side (JavaScript)

### ISSUE THREAD

**Issue by JPrasanna** [MiloszKrajewski/lz4net#15]
Hi,

I'm using LZ4 for compressing my file in C# as mentioned in the URL (https://github.com/MiloszKrajewski/lz4net). Below is the piece of code I'm using for compression.

[HttpGet]
        public IHttpActionResult CompressDataUsingLZ4(string filePath)
        {
            try
            {
                byte[] response;
                byte[] bytes = System.IO.File.ReadAllBytes(filePath);
                response = LZ4Codec.EncodeHC(bytes, 0, bytes.Count());
                string result = System.Text.Encoding.UTF8.GetString(response);
                return Ok(result);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

The API responds with the compressed string to my client side, where I want to decompress my compressed string.

I would like to know whether this is achievable using LZ4.

Could anyone give your thoughts and inputs on this.

Thanks in advance.

**Comment by MiloszKrajewski** [comment]
You seem to do it wrong. Encode is low level stuff which need to understand what it does and doesn't do. Much better:
* LZ4Stream: if you need a stream
* Wrap/Unwrap: if you want to use byte array

In your case I would suggest: LZ4Codec.Wrap(originalBytes) and LZ4Codec.Unwrap(compressedBytes) on the other side.

**Comment by JPrasanna** [comment]
Hi,

Thank you for your reply.

So based on your suggestion I'm using *LZ4Codec.Wrap(originalBytes)* in my
C# code to compress my string, I would like to know where can I find
LZ4Codec.Unwrap(*compressedBytes) *for JavaScript.

As of now I'm using "lz4.js" from the below link

*https://github.com/pierrec/node-lz4 <https://github.com/pierrec/node-lz4>*

Could you please help me on this regard.

**Comment by MiloszKrajewski** [comment]
Oh, I assumed your "client" is another C# application. 
Unfortunately, I don't know what lz4.js do or doesn't do, but both LZ4Stream and Wrap/Unwrap are not part of LZ4 protocol, you most likely need to implement some boxing/unboxing protocol on both sides yourself.
