### ISSUE TITLE
Updated from 1.0.10.93 to 1.0.14.93-> System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Rainer1** [MiloszKrajewski/lz4net#16]
I updated the nuget package in my project to the recent version.
Now I get failing unit tests when calling System.IO.Compression.ZipFile.CreateFromDirectory.
What can I do about that?

The error Message:
============
Test Name:	Writes_given_files_into_archive
Test FullName:	X1.XPrep.Testing.UnitTests.Common.The_DiagnosisArchiveWriter.Writes_given_files_into_archive
Test Source:	C:\Entwicklung\Projekte\XPrep\Main\Source\Testing.UnitTests\Common\The_DiagnosisArchiveWriter.cs : line 44
Test Outcome:	Failed
Test Duration:	0:00:00,6470066

Result StackTrace ......
bei System.IO.Compression.ZipFile.DoCreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, Nullable`1 compressionLevel, Boolean includeBaseDirectory, Encoding entryNameEncoding)
   bei System.IO.Compression.ZipFile.CreateFromDirectory(String sourceDirectoryName, String destinationArchiveFileName, CompressionLevel compressionLevel, Boolean includeBaseDirectory)
   bei X1.XPrep.Common.Classes.DiagnosisArchiveWriter.WriteToFile(IEnumerable`1 allPaths, String targetFilePath) in C:\Entwicklung\Projekte\XPrep\Main\Source\Common\Classes\DiagnosisArchiveWriter.cs:Zeile 89.
   bei X1.XPrep.Testing.UnitTests.Common.The_DiagnosisArchiveWriter.Writes_given_files_into_archive() in C:\Entwicklung\Projekte\XPrep\Main\Source\Testing.UnitTests\Common\The_DiagnosisArchiveWriter.cs:Zeile 51.
Result Message:	
Test method X1.XPrep.Testing.UnitTests.Common.The_DiagnosisArchiveWriter.Writes_given_files_into_archive threw exception: 
System.IO.FileNotFoundException: Die Datei oder Assembly "System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.

**Comment by MiloszKrajewski** [comment]
Apparently System.IO.Compression is missing and I have no idea why. Wrong framework version? Can you build a demo app to reporduce this problem? Thanks.

**Comment by Rainer1** [comment]
I extracted the class and test in question and build an example solution to reproduce the error, but I can not reproduce the error. I could do the updating with out any issues.

Next I decided to "unmap" our solution from TFS, delete the solution folder and remap my solution to TFS, hereby downloading our solution in its previous state. Now I can't update at all, getting a new Error "Failed to add reference to 'System.Runtime.InteroptServices.RuntimeInformation'.

the difference to my last try: I in the meanwhile did some other nuget package updates, which went successfull (all 2036 Unittests green afterwards).

I know, this information must be unsatisfying for you :-(
Unfortunately I can't handout our complete solution due to company restrictions.

Best Regards
Rainer

**Comment by MiloszKrajewski** [comment]
I'm really sorry but I cannot think about anything obvious. Is it .NET 4.5, or .NET 4.6, or .NET Core? There was a change between 4.5 and 4.6 how system (including System.IO.Compression) assemblies are referenced. Maybe something is wrong here (and correlation with lz4net being upgraded is just a coincidence).
I can see stack trace showing "System.IO.Compression.ZipFile.DoCreateFromDirectory". This function is definitely NOT used anywhere in lz4net.

**Comment by Rainer1** [comment]
In our Project, we are using .Net4.6.1
Could it be, that .Net Standard conflicts with .Net4.6.1?
If yes, what would be the best way to continue to use nuget packages, depending on .Net Standard?
To day I tried to update to the new automapper which also now depends on .Net Standard and again I have a simular problem "The file or Assembly "AutoMapper, Version=4.2.1.0,... not found.."

**Comment by MiloszKrajewski** [comment]
lz4net does not depend on .NET Standard. I mean the package contains multiple assemblies in it:
* net2
* net4
* pcl
* netcore

The confusion comes from the fact *netcore* depends on .NET Standard, but *net2*, *net4* and *pcl* depend on NOTHING. So in package dependencies it looks like all depends on .NET Standard and other sections are just empty.

**Comment by Rainer1** [comment]
The Screenshot points out, that .Net Standard will bi installed along with the update.....
![netstandard](https://cloud.githubusercontent.com/assets/9027052/24043910/2fac5bac-0b19-11e7-89ed-f4efc0dfbc56.JPG)

**Comment by MiloszKrajewski** [comment]
You might be right then. I've changed other frameworks to explicitly say "NO DEPENDENCIES". Can you try 1.0.15.93?

**Comment by Rainer1** [comment]
I was able to update to 1.0.15.93 without any problems. 
Thank you very much!

Best Regards
Rainer
