### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by jeffryang24** [MiloszKrajewski/lz4net#17]
Dear, lz4net's Author. I could not find any active documentation for this project in your old codeplex repo, and this github also does not provide any sample code in the README.md file so I can't easily use this library with the right way. Now, I'm trying to understand how to use this library from your Test code :) lol!!

Thanks for creating this amazing library!!!

**Comment by Dharin-shah** [comment]
+1

**Comment by MiloszKrajewski** [comment]
I've added a section on usage on the bottom of main README

**Comment by jeffryang24** [comment]
Ok.. I will check it... Thanks btw....
