### ISSUE TITLE
App does not compile on Xamarin.UWP using .NET Native in release mode

### ISSUE THREAD

**Issue by Capt-Nemo-** [MiloszKrajewski/lz4net#19]
Hi, first of all, very nice library you got there, having lot of fun with it :) good work!

Anyway, as the title says, my Xamarin.UWP app I use for testing does not compile in release mode when the .net native compilation tool chain is turned on (in project settings). Standard .nuget lz4net package is referenced.

You get very cryptic error in the build results window (this is from resharper's build output but it's gonna be the same for stock visual studio's):

`Error: ILT0005: 'C:\<snip>\.nuget\packages\microsoft.net.native.compiler\1.6.1\tools\x86\ilc\Tools\Gatekeeper.exe @"C:\<snip>\obj\x86\Release\ilc\intermediate\gkargs.rsp"' returned exit code 1 (1, 1)`

But turning verbose mode for msbuild reveals the true cause:
`LZ4pn : Gatekeeper error GK0002 : GK0002 Arrays of pointers are not yet implemented. Use array of IntPtr as an alternative.`

Any chance those "pointer arrays" gonna get refactored/worked-around?

**Comment by MiloszKrajewski** [comment]
As it says: "Arrays of pointers are not **yet** implemented" (emphasis on "yet") I guess they are working on  it. The problem, I guess, is related to limited support for "unsafe", and the whole point of "LZ4pn" is unsafe code. 
But... If you distribute "LZ4.dll" without "LZ4pn.dll" it will work **just fine**. It just won't take advantage of unsafe code. This has relatively high performance implication but at least works...

**Comment by Capt-Nemo-** [comment]
Yea I'm fully aware it says "yet", thing is, with microsoft "not yet" can easily translate to "won't fix".

Anyway, if you didn't actually stop reading there you would notice the second part of the error. Where it provides an alternative ie. "**Use array of IntPtr**".
Now I didn't look at the source (**yet**) I can't tell how complex such refactoring would be so you be the judge of that but depending on what you do with those pointer arrays and how you use them it could mean next to no performance hit.

But you're right that the .net native compiler might have problem with unsafe code in general (it has "native" in name and can't use pointers, get it? :)
That after this particular problem is fixed next one will turn up etc. It would have to tested first I guess, to be sure. I might even try it myself later (both testing the current capabilities and refactoring lz4pn, depends on the size of the codebase) as it seems like fun and good to know stuff, will report back to you if that turned up anything useful.

In any case, you might want to consider putting a warning or another asterix in the project description somewhere saying the library won't compile with .net native for windows store apps (which should be all of them nowadays as .net native rocks). Like I stated before the error you originally get in VS is rather cryptic and doesn't directly point to lz4net...

**Comment by MiloszKrajewski** [comment]
https://github.com/MiloszKrajewski/K4os.Compression.LZ4
