### ISSUE TITLE
Destination buffer offset.

### ISSUE THREAD

**Issue by itapi** [MiloszKrajewski/lz4net#21]
Hi!
I'm using this great wrapper in my project...and i need to compress data into another buffer (allocated already) but also with offset of the destination buffer... i mean i need the compressed data to be written in the dest buffer from the `X` position...

`Compress()` doesn't have any overload with destination offset....

What do you suggest me to do?

**Comment by MiloszKrajewski** [comment]
```LZ4Codec.Encode(inputBuffer, inputOffset, inputLength, outputBuffer, outputOffset, maximumLength)```
```LZ4Codec.Decode(inputBuffer, inputOffset, inputLength, outputBuffer, outputOffset, outputLength, knownOutputLength)```
See "Compatibility" section for some usage examples.

**Comment by itapi** [comment]
@MiloszKrajewski  lolololol

I'm so sorry ...haha. i got confused between this repository  https://github.com/khalidsalomao/lz4-net and between yours...

I should ask it there.... XD
