### ISSUE TITLE
Missing libraries at runtime under NetStandard 1.1

### ISSUE THREAD

**Issue by lostromb** [MiloszKrajewski/lz4net#25]
Sorry I haven't fully diagnosed this issue yet, but I'm volunteering to be a guinea pig if you need.
I have a .Net Standard 1.1 project which imports the latest LZ4 package from nuget. This project compiles fine. Then, I have a test project which targets net45 and runs tests against the core project. This also compiles fine, but when it runs it complains that the library "LZ4" could not be found at runtime.

I also notice that lz4net or lz4net.unsafe do not appear inside my package cache, not does lz4net.unsafe get added as a reference to my netstandard project. I'm guessing that the package importer chose not to use unsafe code, but then the runtime detection decided to and then choked when it couldn't find the native lib?  I'm just guessing here.

**Comment by MiloszKrajewski** [comment]
I have no idea to be honest. But I guess, as lz4net has separate assemblies for netcore and net45, you .net standard project "links" again netcore assemblies, and then net45 project pull transitive dependecies as net45. What is the size lz4.dll is obj folder in net45 project? Does it match netstandard release or net45 release?

**Comment by lostromb** [comment]
It's 38,400 bytes. But the thing is, it's never actually copied into the project output directory. I had to find it inside my nuget cache.

I think the problem is that your .nuspec lists LZ4.dll as a <reference> rather than as a <file>. From what I understand in the [.nuget documentation](https://docs.microsoft.com/en-us/nuget/schema/nuspec#explicit-assembly-references), the <reference> tag adds a design-time reference to a library but does not copy it to the runtime directory. Just doing a cursory check, most nuget packages do not use <references> at all.

**Comment by MiloszKrajewski** [comment]
See "FYI" on "Home page"

**Comment by MiloszKrajewski** [comment]
https://github.com/MiloszKrajewski/K4os.Compression.LZ4
