### ISSUE TITLE
NetStandard library DLL has improper version number; fails to load at runtime

### ISSUE THREAD

**Issue by lostromb** [MiloszKrajewski/lz4net#26]
I have a project structure like this:
PortableProject (.Net Standard 1.1) -> depends on lz4net NuGet 1.0.15.93
WebServiceProject (.Net 4.6) -> depends on PortableProject as well as lz4net NuGet 1.0.15.93

WebServiceProject compiles fine but at runtime I am presented with this error:
"Could not load file or assembly 'LZ4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",

What I believe is happening is that PortableProject is being compiled against the NetStandard lz4 library, which has version 1.0.0.0 set in its assembly attributes. However, when I build WebServiceProject, it pulls in the net4-client export from the NuGet package, which has dll version 1.0.15.93, and the runtime complains because it doesn't look like the right library.

This might also be related to the issue I brought up earlier where the .nuspec improperly declares `<reference file="LZ4.dll" />` rather than a normal `<file>`

**Comment by lostromb** [comment]
It's also possible that other attributes of the dll, e.g. Product, OriginalFileName, etc. may not be matching between different versions

**Comment by MiloszKrajewski** [comment]
https://github.com/MiloszKrajewski/K4os.Compression.LZ4
