### ISSUE TITLE
.NET Standard 1.0 assembly has incorrect version and no signature

### ISSUE THREAD

**Issue by jorgebay** [MiloszKrajewski/lz4net#28]
Assembly information:
- Net 4 client profile assembly: `LZ4, Version=1.0.15.93, Culture=neutral, PublicKeyToken=62e1b5ec1eec9bdd` ✅ 
- netstandard1.0 profile assembly: `LZ4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null` ❎  

Given that most platforms support .netstandard 1.0, it's likely that #26 and #25 are caused by this issue.

The solution is to assign the [correct version on the project.json file](https://github.com/MiloszKrajewski/lz4net/blob/dcb781de47294fbec5cf87a3094090b4deb41a51/src/LZ4.netcore/project.json#L2) and set the keyfile in the build options:
```json
{
  "buildOptions": {
    "keyFile": "MyKey.snk"
  }
}
```

Also, if you are interested in migrating, .NET Tools are out of preview mode and there is a new "unified" csproj format (VS2017): https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj

**Comment by MiloszKrajewski** [comment]
Thank you. I struggled with that a lot. Maintaining comaptibility with .NET2, .NET4, PCL and .NET Standard is painful. I still want (full) .NET compatibility as "mixed mode" implementation is much faster. I'm considering splitting it into two separate packages families.

**Comment by vpenades** [comment]
I am having this issue too... is there a solution for this already?

**Comment by MiloszKrajewski** [comment]
I've re-ported whole thing into separate repo (https://github.com/MiloszKrajewski/K4os.Compression.LZ4) supporting .NET Standard 1.6+. I would be great if you could give it a try as well. Thanks.

**Comment by vpenades** [comment]
There's nugets already? sure will try!

Thanks!
