### ISSUE TITLE
Use case for seekable stream

### ISSUE THREAD

**Issue by rraallvv** [MiloszKrajewski/lz4net#33]
I'm trying to use lz4net and CryptoStream to compress and encrypt each individual file within a directory, and then to merge them all into a single file.

Now I'd like to be able to extract a single file but neither lz4net nor CryptoStream are seekable.

At least for CryptoStream I could find a [solution](https://stackoverflow.com/a/38974483/1436359) but I'm not sure about lz4net. Is there an easy way make lz4net seekable given that the internal state wouldn't need to be preserved? Since each time the stream changes its position would be to read a different embedded file.

Keep up the good work!

**Comment by MiloszKrajewski** [comment]
Compressed stream are generally (always?) not seekable. Sometimes compressed containers (for example: zip) have manifest listing all files in it with offsets, but deflate stream itself is not seekable.
