### ISSUE TITLE
error unpack

### ISSUE THREAD

**Issue by Form1ca** [MiloszKrajewski/lz4net#34]
Exception when unpacking this file
[0000_00B0.cr32.zip](https://github.com/MiloszKrajewski/lz4net/files/2134698/0000_00B0.cr32.zip)

> byte[] filedata = System.IO.File.ReadAllBytes(@"C:\0000_00B0.cr32.dat ");
byte[] filedata2 = LZ4Codec.Decode(filedata, 0, filedata.Length, 0x1434b);//"LZ4 block is corrupted, or invalid length has been given."

0x1434b - unpacked size

i correct unpack this file by another language

**Comment by MiloszKrajewski** [comment]
https://github.com/MiloszKrajewski/lz4net/blob/master/doc/compatibility.md
