### ISSUE TITLE
Python Compatibility?

### ISSUE THREAD

**Issue by Jayatubi** [MiloszKrajewski/lz4net#35]
I tried to use `LZ4Codec.Encode` and `LZ4Stream` to compress my data and then uncompress in python. However, it failed with error `LZ4F_getFrameInfo failed with code: ERROR_frameType_unknown`.

I checked the `Compatibility` section on the home page `Readme` and tried such code:

```
var buffer = new byte[LZ4.LZ4Codec.MaximumOutputLength(body.Length)];
var compressedLength = LZ4.LZ4Codec.Encode(body, 0, body.Length, buffer, 0, buffer.Length);
deflateBody = new byte[compressedLength];
Array.Copy(buffer, deflateBody, compressedLength);
````

But this doesn't work neither.

How can I make the compressed data to be compatible with the Python's?

**Comment by UlyssesWu** [comment]
Although I have seen your `lz4-unity` repo, I just made a managed (pure C#) solution here: 

https://github.com/UlyssesWu/LZ4.Frame

(It's not a complete implementation, but should handle most situations.)

**Comment by MiloszKrajewski** [comment]
https://github.com/MiloszKrajewski/lz4net/blob/master/doc/compatibility.md
