### ISSUE TITLE
Chunks with multiple passes are not supported

### ISSUE THREAD

**Issue by realivanjx** [MiloszKrajewski/lz4net#39]
I know this is related to this issue #6 but i cant understand that issue very well so i posted this error again here. What im trying to do is to decompress an `lz4` file. I already tested the lz4 sample file with lz4 decompressor so the file is not the problem. Here is my code to decompress:

```
 using (Stream infs = File.Open(inputFilePath, FileMode.Open))
 using (LZ4Stream lz4Stream = new LZ4Stream(infs, LZ4StreamMode.Decompress))
 using (Stream outfs = File.Open(outputFilePath, FileMode.Create))
 {
    lz4Stream.CopyTo(outfs, 1024 * 1024);
 }
```

The exception occurs at the `CopyTo` function. What i've been missing? 

Thanks.

**Comment by MiloszKrajewski** [comment]
I guess this is the answer:
https://github.com/MiloszKrajewski/lz4net/blob/master/doc/compatibility.md
