### ISSUE TITLE
Support LeaveOpen

### ISSUE THREAD

**Issue by naster01** [MiloszKrajewski/lz4net#4]
Hi, when closing the stream, the base stream should not be closed.

I would have commit but I got few problems with targets when upgrading to Framework 4.5.2.

Here a small fix :

	public LZ4Stream(
		Stream innerStream,
		LZ4StreamMode compressionMode,
		bool highCompression = false,
		int blockSize = 1024*1024,
		bool interactiveRead = false, 
		bool leaveOpen = false)
	{
		_innerStream = innerStream;
		_compressionMode = compressionMode;
		_highCompression = highCompression;
		_interactiveRead = interactiveRead;
		_blockSize = Math.Max(16, blockSize);
		_leaveOpen = leaveOpen;
	}

	protected override void Dispose(bool disposing)
	{
		Flush();
		if(!_leaveOpen)
			_innerStream.Dispose();
		base.Dispose(disposing);
	}

**Comment by MiloszKrajewski** [comment]
FYI: has been addressed but neither tested or relased

**Comment by MiloszKrajewski** [comment]
Fixed in 1.0.10.93, see LZ4StreamFlags.IsolateInnerStream
