### ISSUE TITLE
Can't compress bitmap stored as byte[] using lz4net (Version:1.0.15.93)

### ISSUE THREAD

**Issue by sbalaketheeswaran** [MiloszKrajewski/lz4net#40]
I have been trying to use the available NuGet package of lz4net (Version:1.0.15.93) to compress a bitmap quickly. Motivation is to log incoming bitmaps to disk from a Frame grabber which dispenses frames every 30 ms. 

Here is the concerning code snippet

        private void Lz4Compression()
        {
            try
            {
                using (FileStream fs = new FileStream(m_outputPath, FileMode.Create))
                {
                    using (LZ4Stream stream = new LZ4Stream(fs, LZ4StreamMode.Compress))
                    {
                        using (BinaryWriter writer = new BinaryWriter(stream))
                        {
                            writer.Write(m_loadedImage);
                        }
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }

The resulting compressed file is of "almost" the same size in bytes as the original bitmap loaded as a byte[], m_loadedImage.

Does the compression not work when using a BinaryWriter instead of a StreamWritter? 
When I followed the Lorem Ipsum example, text only, I had great compression results.

Any feedback would be greatly appreciated.

**Comment by MiloszKrajewski** [comment]
As mentioned on front page LZ4 is fast but "sacrificing compression ratio for compression/decompression speed". 

* Lorem Ipsum example compresses well as it is same text repeated many times
* Use high compression (it is slower, but gives better compression ratio)
* You can try increasing block size

On top of that:

* Don't use BinaryWriter just use Stream directly (does not affect size though, it is just a performance)

**Comment by sbalaketheeswaran** [comment]
Very much appreciate the feedback! I've made your suggested changes, but as you have highlighted I am still encountering the compression ratio issue using the following code.

     private void Lz4Compression()
        {
            try
            {
                using (FileStream fs = new FileStream(m_outputPath, FileMode.Create))
                {
                    using (LZ4Stream stream = new LZ4Stream(fs, LZ4StreamMode.Compress, Z4StreamFlags.HighCompression, 1048576 * 5))
                    {
                        stream.Write(m_loadedImage, 0, m_loadedImage.Length);
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
        }

I will investigate alternative options. Thanks!
