### ISSUE TITLE
netstandard2.0

### ISSUE THREAD

**Issue by JBaltika** [MiloszKrajewski/lz4net#42]
Hi,
Is this library still maintain? Any change netstandard 2.0 release?

**Comment by MiloszKrajewski** [comment]
https://github.com/MiloszKrajewski/lz4net/blob/master/README.md

> This library is no longer maintained and has been replaced by K4os.Compression.LZ4.
> K4os.Compression.LZ4 is a port of lz4 1.8.1 (latest stable @ 2018-02-01) for .NET Standard and handles both BLOCK and STREAM modes.
