### ISSUE TITLE
Lz4Net 'crashes' on Unity 3D engine Armv7.apk(s) from aab google bundle files using IL2CPP option.

### ISSUE THREAD

**Issue by pepoon** [MiloszKrajewski/lz4net#43]
Hey MiloszKrajewski,
My first time posting on github so I apologize for any mistake I do.

  private static readonly LZ4DecoderSettings Lz4DecoderSettings = new LZ4DecoderSettings
        {
            ExtraMemory = 0,
        };
 private static Stream DecompressInternal(Stream inStream)
        {
            var decodeStream = LZ4Stream.Decode(inStream, Lz4DecoderSettings, false);
            var outStream = new MemoryStream();
            decodeStream.CopyTo(outStream); <------- It crashes.
            return outStream;
        }

So we are compressing our AssetBundles using LZ4 library, It works nicely on Armv64 and pcs so I'm asuming that 64bit systems works well. Unity uses IL2CPP.

IL2CPP => IL2CPP (Intermediate Language To C++) is a Unity-developed scripting backend
 which you can use as an alternative to Mono when building projects for various platforms.
https://docs.unity3d.com/Manual/IL2CPP.html

So it seems that converting the IL to c++ for 32bit systems causes Lz4Net not to work properly,
I cant point exacly where it is failing, since I'm not getting an StackTrace from the LogCat that I use to debug android apps.

Any Idea of how to find a solution for this? Im using this library because it is fascinating FAST!
Thanks in advance.

**Comment by MiloszKrajewski** [comment]
I'm pretty sure you posted it on wrong repo. Source to showed suggests https://github.com/MiloszKrajewski/K4os.Compression.LZ4.

I'm also guessing that you are referring to this problem: https://github.com/MiloszKrajewski/K4os.Compression.LZ4/issues/19 which has been fixed but unfortunately fix is still in beta release only.

**Comment by pepoon** [comment]
yea sorry.

**Comment by pepoon** [comment]
I'm not sure If I can post to a closed Thread but I did just in case others
need that.

I copied the post here just in case. Many thanks Miko.

====================================
I tested that on Samsung Galaxy s5(Armvv7) and it crashes..

What I'm doing is:

   - Get the repository in VS using nuget.
   - Import the libs & dependences to UNITY.

But once I Deploy to Armv7 IL2CPP it crashes,
Then I checked the repository and i found these lines:
namespace K4os.Compression.LZ4.Engine

  | {
  | #if BIT32
  | internal unsafe class LZ4_32: LZ4_xx
  | {
  | ...
  | #else
  | internal unsafe class LZ4_64: LZ4_xx
  | { }

That means to make it work on Armv7 devices, I need to pull the solution
and define/or not the #32BIT processor, get the .dlls and use them in UNITY
to make it work on Armv7?
Are these the steps?
Thanks.

Missatge de Milosz Krajewski <notifications@github.com> del dia dj., 28 de
maig 2020 a les 9:59:

**Comment by pepoon** [comment]
I finally could reproduce the bug, Here are the logcat logs and an apk with
IL2CPP armv7 & armb64.
Pushing the Unity project as well later.
It is trying to decompress a file. On armv64 it works while on armv7
crashes.
 arm7-logs.txt
<https://drive.google.com/file/d/1q2_uWqv6Q-xtjebVzAm_a4EWCL9GR6Cm/view?usp=drive_web>
 arm64-logs.txt
<https://drive.google.com/file/d/1_g9-JyQ16e0HrKuDlMoNA8yrzlgozd-2/view?usp=drive_web>
 lz4-test2-arm7-64-.apk
<https://drive.google.com/file/d/1OLa81yuTJKstwAIyCofYuWfSh24SSjZ7/view?usp=drive_web>


Missatge de Josep Maria Calull Mercadé <calullmercade@gmail.com> del dia
dj., 28 de maig 2020 a les 15:37:

**Comment by pepoon** [comment]
Hey Milos,

Unity managed to reproduce the bug(lz4):
If you want to attach the link to your github repo, here it is:
https://issuetracker.unity3d.com/issues/armv7-il2cpp-build-crash-when-using-custom-compression


Thanks

Missatge de Josep Maria Calull Mercadé <calullmercade@gmail.com> del dia
dv., 29 de maig 2020 a les 10:27:
