### ISSUE TITLE
Cannot decompress data that was compressed with C implementation

### ISSUE THREAD

**Issue by o-mdr** [MiloszKrajewski/lz4net#7]
I am working with the multi-OS system. Client apps are written in C and server apps are in C#. The problem is I cannot decompress messages that were compressed with LZ4 C implementation. The error that I get is 

> LZ4 block is corrupted, or invalid length has been given.

To make a small reproducible example, I compressed a string on an Ubuntu machine

``` shell
sudo apt-get install liblz4-tool
echo -n '[{"d":"2016-02-19T00:00:00.000Z","ac":"machine on","u":"foo__bar","m":"m1"}]' | lz4 -zl | xxd -i -c 10
 0x02, 0x21, 0x4c, 0x18, 0x4d, 0x00, 0x00, 0x00, 0xf1, 0x06,
  0x5b, 0x7b, 0x22, 0x64, 0x22, 0x3a, 0x22, 0x32, 0x30, 0x31,
  0x36, 0x2d, 0x30, 0x32, 0x2d, 0x31, 0x39, 0x54, 0x30, 0x30,
  0x3a, 0x03, 0x00, 0xf0, 0x23, 0x2e, 0x30, 0x30, 0x30, 0x5a,
  0x22, 0x2c, 0x22, 0x61, 0x63, 0x22, 0x3a, 0x22, 0x6d, 0x61,
  0x63, 0x68, 0x69, 0x6e, 0x65, 0x20, 0x6f, 0x6e, 0x22, 0x2c,
  0x22, 0x75, 0x22, 0x3a, 0x22, 0x66, 0x6f, 0x6f, 0x5f, 0x5f,
  0x62, 0x61, 0x72, 0x22, 0x2c, 0x22, 0x6d, 0x22, 0x3a, 0x22,
  0x6d, 0x31, 0x22, 0x7d, 0x5d
```

I saved compressed bytes in a [file](http://turl.ca/foolz4) and was able to decompress the content successfully on a different Windows machine using [lz4.exe](http://fastcompression.blogspot.co.uk/p/lz4.html) with the following command `lz4 -d foo.lz4`.

However, I cannot decompress these bytes in C#. I have built a self-contained test (.Net 4.6 VS 2015, but other versions I'd assume will give the same error).

``` cs
using System.Text;
using LZ4;
using NUnit.Framework;

namespace Transport.Tests
{
    [TestFixture]
    public class Lz4Test
    {
        // to get payload on Ubuntu (or other Linuxie or Unixie) machine
        // sudo apt-get install liblz4-tool
        // echo -n '[{"d":"2016-02-19T00:00:00.000Z","ac":"machine on","u":"foo__bar","m":"m1"}]' | lz4 -zl | xxd -i -c 10
        byte[] payload = {
              0x02, 0x21, 0x4c, 0x18, 0x4d, 0x00, 0x00, 0x00, 0xf1, 0x06,
              0x5b, 0x7b, 0x22, 0x64, 0x22, 0x3a, 0x22, 0x32, 0x30, 0x31,
              0x36, 0x2d, 0x30, 0x32, 0x2d, 0x31, 0x39, 0x54, 0x30, 0x30,
              0x3a, 0x03, 0x00, 0xf0, 0x23, 0x2e, 0x30, 0x30, 0x30, 0x5a,
              0x22, 0x2c, 0x22, 0x61, 0x63, 0x22, 0x3a, 0x22, 0x6d, 0x61,
              0x63, 0x68, 0x69, 0x6e, 0x65, 0x20, 0x6f, 0x6e, 0x22, 0x2c,
              0x22, 0x75, 0x22, 0x3a, 0x22, 0x66, 0x6f, 0x6f, 0x5f, 0x5f,
              0x62, 0x61, 0x72, 0x22, 0x2c, 0x22, 0x6d, 0x22, 0x3a, 0x22,
              0x6d, 0x31, 0x22, 0x7d, 0x5d
        };

        [Test]
        public void DecompressTest()
        {
            // Act
            string codec = LZ4Codec.CodecName;
            // tried with 
            // MixedMode 64/MixedMode 64/MixedMode 64HC
            // MixedMode 32 / MixedMode 32 / MixedMode 32HC

            byte[] actual = LZ4Codec.Unwrap(payload);  // << FAILS here
            // Error message: LZ4 block is corrupted, or invalid length has been given.
        }
    }
}
```

**Comment by o-mdr** [comment]
If I use `LZ4Codec.Decode` and tell it all the parameters - it works, but I have to skip the header, first 8 bytes. I cannot do this in production though.

```cs
// this works
byte[] actual = new byte[81];
LZ4Codec.Decode(payload, 8, payload.Length - 8, actual, 0, 81);
```

**Comment by MiloszKrajewski** [comment]
Explanation: 
http://cyan4973.github.io/lz4/ lists all implementations. LZ4.net is listed in section "Multiple languages" described as "Each version encapsulates the compressed result into its own header/frame format convention."

Long story short: *block data* is compatible with original (Yann's) LZ4 implementation, the *block header* is not. Feel free to implement parsing original (Yann's) block header. You can also easily implement your own header on both sides.

**Comment by o-mdr** [comment]
Thanks for your reply. That's what I thought as well, it's a custom header. We decided to use gzip (fastest option) just now. But would like to go back to LZ4 in future. I might work on this in spare time.

Going forward, if one implements this custom header, how do you see this integrate into the current library? Should it be a fork with a new name or will you be willing to merge the header into the current source code? If the later, it will be a breaking change in the library.

What are your thoughts on this?
Can you also please point out the best place to put new implementation in and the documentation for the format?
Are there any reasons for custom header to exist?
