### ISSUE TITLE
Port in CoreCLR

### ISSUE THREAD

**Issue by BDeus** [MiloszKrajewski/lz4net#9]
Hi,
it can be cool to port this library as the first LZ4 Lib available in new dotnet core.
I think the c++ library cannot be port (because vc++ compiler not available in core clr) but the unsafe and safe c# can be.
What do you think?

**Comment by MiloszKrajewski** [comment]
Won't it run "portable"?

**Comment by BDeus** [comment]
no you need to create a whole new project (xproj) and to check and correct compatibilty.
I can try to create a new branch with that if you want

**Comment by MiloszKrajewski** [comment]
I guess I would need VS2015 for that? I'm still on VS2013.

**Comment by BDeus** [comment]
probably yes

**Comment by BDeus** [comment]
has an example i have commit a new solution on this branch https://github.com/BDeus/lz4net/tree/CoreCLR

**Comment by BDeus** [comment]
the new coreclr framework is still in release candidate an not production ready but it can be cool to have it ready when it becomes stable.
i actually work on kafka c# library in coreclr and have a lz4net lib ready can help me :)

**Comment by manigandham** [comment]
Hi @MiloszKrajewski, are you already working on this?

.NET Core is now released: https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/

.NET 4, 4.5 and 4.5.1 are also deprecated: https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by manigandham** [comment]
Hey @MiloszKrajewski, based on your earlier comment about VS2015, the .NET team has said that it's not necessary and that the CLI should be enough or the free Visual Studio Community version.

**Comment by ilushka85** [comment]
Are there any updates on this?

**Comment by MiloszKrajewski** [comment]
It's the next thing I'll be working on. Although, I have some personal issues at this very moment, so it not working on this now.

**Comment by arpit-nagar** [comment]
Do you have any timelines on it ?

**Comment by MiloszKrajewski** [comment]
.NET Standard 1.6 version release. "Safe" is the only working version so far, but it can be used already (not too fast for a while, though).
